### ISSUE TITLE
wrapPCs might be checked before try to read values from there. panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by ksaritek** [rotisserie/eris#91]
**Describe the bug**
while using Wrap or Wrapf, wrapPCs stack array must be checked before getting values from it. it is not always populated, for instance, if you are in a go routine, then you have no stack trace there. I put a code snippet for that.

**To Reproduce**
1. run the below go code
```
package main

import (
	"fmt"
	"time"

	"github.com/rotisserie/eris"
)

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("Recovered in f", r)
		}
	}()

	go func() {
		err := dummyStack()
		fmt.Println(eris.Wrap(err, "my wrap func").Error())
	}()

	time.Sleep(1 * time.Second)
}

func dummyStack() error {
	return eris.New("my little tiny error")
}

```
2. See error

**Expected behavior**
stack operation needs to be enhanced. So, when you call Wrap in the go routine or main go routine, there is no stack to use in wrap.
code steps are:
https://github.com/rotisserie/eris/blob/master/eris.go#L69
https://github.com/rotisserie/eris/blob/master/stack.go#L90

and boom 

**Screenshots**
```
panic: runtime error: index out of range [0] with length 0

goroutine 18 [running]:
github.com/rotisserie/eris.(*stack).insertPC(0xc000102000, 0xc000100200, 0x0, 0x40)
        /go/pkg/mod/github.com/rotisserie/eris@v0.4.0/stack.go:90 +0x303
github.com/rotisserie/eris.wrap(0x10f3420, 0xc000106030, 0xc000108020, 0xc, 0xc, 0xc000106030)
        /go/pkg/mod/github.com/rotisserie/eris@v0.4.0/eris.go:69 +0x351
github.com/rotisserie/eris.Wrap(0x10f3420, 0xc000106030, 0x10d5d1d, 0xc, 0x0, 0x0)
        /go/pkg/mod/github.com/rotisserie/eris@v0.4.0/eris.go:38 +0xa3
main.main.func2()
        /go/cmd/playground.go:19 +0x67
created by main.main
        /go/cmd/playground.go:17 +0x57
exit status 2

```

**Desktop (please complete the following information):**
 - OS: [iOS]

**Additional context**
before inserting stack, it might be good to check have a stack first, but i don't know how will change stack formating
```
// insertPC inserts a wrap error program counter (pc) into the correct place of the root error stack trace.
func (s *stack) insertPC(wrapPCs stack) {
	if len(wrapPCs) == 1 {
		// append the pc to the end if there's only one
		*s = append(*s, wrapPCs[0])
		return
	}
	for at, f := range *s {
////===>> we don't know we have a stack at wrapPC ???
 		if f == wrapPCs[0] {
			// break if the stack already contains the pc
			break
		} else if f == wrapPCs[1] {
			// insert the first pc into the stack if the second pc is found
			*s = insert(*s, wrapPCs[0], at)
			break
		}
	}
}
```

**Comment by morningvera** [comment]
hey @ksaritek, thanks for submitting this detailed bug report! i'll start working on a fix in the next day or two
